### ISSUE TITLE
Issue with config = model.get_config()

### ISSUE THREAD

**Issue by FMCumhaill** [mattdangerw/keras-text-generation#2]
I'm getting the following error just from trying to run train.py 

`Traceback (most recent call last):
  File "train.py", line 42, in <module>
    main()
  File "train.py", line 37, in main
    model.train(**vars(args))
  File "/root/keras-text-generation-master/model.py", line 135, in train
    self._build_models(batch_size, embedding_size, rnn_size, num_layers)
  File "/root/keras-text-generation-master/model.py", line 113, in _build_models
    config[0]['config']['batch_input_shape'] = (1, None)
KeyError: 0
`
Set up:
Anaconda Python 3.6.7 on a Ubuntu 18.10 X64 

There seems to be two errors, firstly on line 112 of model.py, (config = model.get_config()) 
It seems to be hitting an error when trying to index the first model ("[0]"), secondly, it also seems to be having an issue find config['config']. 

This is the first time I've run this code, so is there some requirement to pre install a mode? 

Thanks!

**Comment by Akhu** [comment]
Hey, 
Got the same issue ! You just need to run `pip install -r requirements.txt` before running the project ;)
